# Generated by Django 5.1.7 on 2025-05-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.RemoveField(
            model_name='artpiece',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='artpiece',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='artpiece',
            name='price',
        ),
        migrations.RemoveField(
            model_name='artpiece',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='image',
            field=models.ImageField(upload_to='art_images/'),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='year_created',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='anonymous@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
