# Generated by Django 5.1.7 on 2025-05-06 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_feedback_options_remove_artpiece_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
